import sys
import os

def save_active_platforms(ap, src_dir, tgt_dir):

    for x in ap:
        svg_names = []
        if os.path.isfile(src_dir + "/" + x + "/logo.svg"):
            svg_names.append("logo")
        if os.path.isfile(src_dir + "/" + x + "/run_icon.svg"):
            svg_names.append("run_icon")

        for name in svg_names:
            svgf = open(src_dir + "/" + x + "/" + name + ".svg", "rb")
            b = svgf.read(1)
            svg_str = " /* AUTOGENERATED FILE, DO NOT EDIT */ \n"
            svg_str += " static const char *_" + x[9:] + "_" + name + '_svg = "'
            while len(b) == 1:
                svg_str += "\\" + hex(ord(b))[1:]
                b = svgf.read(1)

            svg_str += '";\n'

            svgf.close()

            # NOTE: It is safe to generate this file here, since this is still executed serially
            wf = tgt_dir + "/" + x + "/" + name + "_svg.gen.h"
            with open(wf, "w") as svgw:
                svgw.write(svg_str)
                
src_dir = sys.argv[1]
tgt_dir = sys.argv[2]

active_platforms = []
active_platform_ids = []

active_platforms.append("Windows")
active_platform_ids.append("platform/windows")

active_platforms.append("macOS")
active_platform_ids.append("platform/macos")


save_active_platforms(active_platform_ids, src_dir, tgt_dir)
